// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SystemMonitorAPI.Model;

#nullable disable

namespace SystemMonitorAPI.Migrations
{
    [DbContext(typeof(SystemMonitorContext))]
    partial class SystemMonitorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemMonitorAPI.Model.BitLockerKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IDENTIFIER");

                    b.Property<string>("PasswordId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORDID");

                    b.Property<string>("RecoveryKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RECOVERYKEY");

                    b.HasKey("Id");

                    b.ToTable("SMM_BITLOCKERKEY");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.Credential", b =>
                {
                    b.Property<int>("CredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CREDENTIALID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialID"));

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENCRYPTEDPASSWORD");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERNAME");

                    b.HasKey("CredentialID");

                    b.ToTable("SMM_CREDENTIAL");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.Device", b =>
                {
                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Department")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LASTUPDATED");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Hostname");

                    b.ToTable("SMM_DEVICE");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.DiskDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Capacity")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("DiskName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DISKNAME");

                    b.Property<double>("FreeSpace")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("FREESPACE");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("TypeOfDrive")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPEOFDRIVE");

                    b.Property<string>("encryptionKey")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENCRYPTIONKEY");

                    b.Property<double>("isEncrypted")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("ISENCRYPTED");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_DISKDETAILS");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.DiskInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Capacity")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("DiskName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DISKNAME");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("InterfaceType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INTERFACETYPE");

                    b.Property<string>("TypeOfDrive")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPEOFDRIVE");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_DISKINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.LocalUserInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISENABLED");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISLOCKED");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERNAME");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_LOCALUSERINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.MonitorDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<string>("SerialNo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SERIALNO");

                    b.Property<string>("YearOfManufacture")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("YEAROFMANUFACTURE");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_MONITORDETAIL");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.NetworkDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("IPAddress")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IPADDRESS");

                    b.Property<string>("InterfaceName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INTERFACENAME");

                    b.Property<string>("MACAddress")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MACADDRESS");

                    b.Property<string>("NetworkType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NETWORKTYPE");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_NETWORKDETAIL");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.PhysicalMemoryInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Capacity")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("DeviceLocator")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DEVICELOCATOR");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<string>("SerialNo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SERIALNO");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_PHYSICALMEMORYINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SoftwareDetail", b =>
                {
                    b.Property<int>("SoftwareDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOFTWAREDETAILSID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareDetailsID"));

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Publisher")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PUBLISHER");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SOFTWARENAME");

                    b.Property<string>("UninstallString")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UNINSTALLSTRING");

                    b.Property<string>("Version")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("VERSION");

                    b.HasKey("SoftwareDetailsID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_SOFTWAREDETAIL");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemDetail", b =>
                {
                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("BIOSSerial")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("BIOSSERIAL");

                    b.Property<string>("Domain")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DOMAIN");

                    b.Property<string>("Make")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MAKE");

                    b.Property<double>("MaxPhysical")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MAXPHYSICAL");

                    b.Property<string>("Model")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MODEL");

                    b.Property<string>("OSName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OSNAME");

                    b.Property<string>("OSVersion")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OSVERSION");

                    b.Property<string>("OUName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OUNAME");

                    b.Property<double>("PhysicalMemory")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PHYSICALMEMORY");

                    b.Property<string>("ProcessorFamily")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PROCESSORFAMILY");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Hostname");

                    b.ToTable("SMM_SYSTEMDETAIL");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemInfo", b =>
                {
                    b.Property<int>("SystemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYSTEMID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemID"));

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HOSTNAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISACTIVE");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LASTUPDATEDATE");

                    b.HasKey("SystemID");

                    b.ToTable("SMM_SYSTEMINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemUpdate", b =>
                {
                    b.Property<int>("SystemUpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYSTEMUPDATEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemUpdateID"));

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LASTATTEMPTDATE");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUSMESSAGE");

                    b.Property<int>("SystemID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYSTEMID");

                    b.Property<int>("UpdateID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UPDATEID");

                    b.HasKey("SystemUpdateID");

                    b.HasIndex("SystemID");

                    b.HasIndex("UpdateID");

                    b.ToTable("SMM_SYSTEMUPDATE");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.UninstallInfo", b =>
                {
                    b.Property<int>("uninstallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UNINSTALLID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uninstallId"));

                    b.Property<int>("Active")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Remarks")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REMARKS");

                    b.Property<int>("applicationId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("APPLICATIONID");

                    b.Property<string>("hostname")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("softwareName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SOFTWARENAME");

                    b.Property<int>("systemId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYSTEMID");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDATE");

                    b.HasKey("uninstallId");

                    b.ToTable("SMM_UNINSTALLINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.UpdateInfo", b =>
                {
                    b.Property<int>("UpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UPDATEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDDATE");

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILENAME");

                    b.Property<string>("FilePath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILEPATH");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Parameters")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PARAMETERS");

                    b.Property<string>("UpdateName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATENAME");

                    b.HasKey("UpdateID");

                    b.ToTable("SMM_UPDATEINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.UpdateLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LOGID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LOGDATE");

                    b.Property<string>("LogMessage")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOGMESSAGE");

                    b.Property<int>("SystemID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SYSTEMID");

                    b.Property<int>("UpdateID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("UPDATEID");

                    b.HasKey("LogID");

                    b.HasIndex("SystemID");

                    b.HasIndex("UpdateID");

                    b.ToTable("SMM_UPDATELOG");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.antivirusInfos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("LastUpdate")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LASTUPDATE");

                    b.Property<string>("ProductState")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PRODUCTSTATE");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_ANTIVIRUSINFOS");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.firewallProfileInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DefaultInboundAction")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DEFAULTINBOUNDACTION");

                    b.Property<string>("DefaultOutboundAction")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DEFAULTOUTBOUNDACTION");

                    b.Property<string>("Enabled")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENABLED");

                    b.Property<string>("Hostname")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("HOSTNAME");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.HasKey("ID");

                    b.HasIndex("Hostname");

                    b.ToTable("SMM_FIREWALLPROFILEINFO");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.DiskDetails", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("DiskDetails")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.DiskInfo", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("diskInfos")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.LocalUserInfo", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("LocalUserDetails")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.MonitorDetail", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("MonitorDetails")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.NetworkDetail", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("NetworkDetails")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.PhysicalMemoryInfo", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("PhysicalMemoryInfo")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SoftwareDetail", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("SoftwareDetails")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemDetail", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("SystemDetails")
                        .HasForeignKey("Hostname")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemUpdate", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.SystemInfo", "SystemInfo")
                        .WithMany("SystemUpdates")
                        .HasForeignKey("SystemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemMonitorAPI.Model.UpdateInfo", "UpdateInfo")
                        .WithMany("SystemUpdates")
                        .HasForeignKey("UpdateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemInfo");

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.UpdateLog", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.SystemInfo", "SystemInfo")
                        .WithMany()
                        .HasForeignKey("SystemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemMonitorAPI.Model.UpdateInfo", "UpdateInfo")
                        .WithMany()
                        .HasForeignKey("UpdateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemInfo");

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.antivirusInfos", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("antivirusInfos")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.firewallProfileInfo", b =>
                {
                    b.HasOne("SystemMonitorAPI.Model.Device", null)
                        .WithMany("firewallProfileInfo")
                        .HasForeignKey("Hostname");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.Device", b =>
                {
                    b.Navigation("DiskDetails");

                    b.Navigation("LocalUserDetails");

                    b.Navigation("MonitorDetails");

                    b.Navigation("NetworkDetails");

                    b.Navigation("PhysicalMemoryInfo");

                    b.Navigation("SoftwareDetails");

                    b.Navigation("SystemDetails");

                    b.Navigation("antivirusInfos");

                    b.Navigation("diskInfos");

                    b.Navigation("firewallProfileInfo");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.SystemInfo", b =>
                {
                    b.Navigation("SystemUpdates");
                });

            modelBuilder.Entity("SystemMonitorAPI.Model.UpdateInfo", b =>
                {
                    b.Navigation("SystemUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
